<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LE40DIL" failures="2" tests="7" name="Command line test" time="6.159" errors="0" timestamp="2025-10-22T21:46:20 WIB">
  <testcase classname="tests.PositiveTests" name="testCreateUserSuccessfully" time="2.691">
    <failure type="java.lang.AssertionError" message="Expected status 201 Created expected [201] but found [401]">
      <![CDATA[java.lang.AssertionError: Expected status 201 Created expected [201] but found [401]
at tests.PositiveTests.testCreateUserSuccessfully(PositiveTests.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at tests.TestRunner.main(TestRunner.java:17)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testCreateUserSuccessfully -->
  <testcase classname="tests.PositiveTests" name="testGetExistingUser" time="0.281"/>
  <testcase classname="tests.NegativeTests" name="testCreateUserWithEmptyBody" time="0.422">
    <failure type="java.lang.AssertionError" message="Expected 400, 415, or 422, but got: 401 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Expected 400, 415, or 422, but got: 401 expected [true] but found [false]
at tests.NegativeTests.testCreateUserWithEmptyBody(NegativeTests.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at tests.TestRunner.main(TestRunner.java:17)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testCreateUserWithEmptyBody -->
  <testcase classname="tests.NegativeTests" name="testGetNonExistingUser" time="0.657"/>
  <testcase classname="tests.BoundaryTests" name="testGetUserWithIdZero" time="0.671"/>
  <testcase classname="tests.BoundaryTests" name="testGetUserWithMaxIntId" time="0.657"/>
  <testcase classname="tests.BoundaryTests" name="testGetUserWithNegativeId" time="0.673"/>
</testsuite> <!-- Command line test -->
